DROP TABLE AVOIR;
DROP TABLE PERMISSION;

INSERT INTO ROLE (ID, LIBELLE, DELETED) VALUES
(1, 'ADMIN', 0),
(2, 'USER', 0);

UPDATE COMPTE SET ID_ROLE = '1' WHERE COMPTE.ID = 2;
UPDATE COMPTE SET ID_ROLE = '2' WHERE COMPTE.ID = 1;
