CREATE TABLE `VERSION` (
  `NUM` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
ALTER TABLE `VERSION`
  ADD PRIMARY KEY (`NUM`);
  
INSERT INTO `VERSION` (`NUM`) VALUES ('0'), ('1'), ('2'), ('3'), ('4');
